// Generated by bun-plugin-auto-imports
export {};
declare global {
  const WebServerArguments: typeof import('./web')['WebServerArguments'];
  const autoImportPlugin: typeof import('./utils')['autoImportPlugin'];
  const isDevelopment: typeof import('./utils')['isDevelopment'];
  const isProduction: typeof import('./utils')['isProduction'];
  const useCallback: typeof import('react')['useCallback'];
  const useContext: typeof import('react')['useContext'];
  const useEffect: typeof import('react')['useEffect'];
  const useMemo: typeof import('react')['useMemo'];
  const useReducer: typeof import('react')['useReducer'];
  const useRef: typeof import('react')['useRef'];
  const useState: typeof import('react')['useState'];
  const webServer: typeof import('./web')['webServer'];
  const z: typeof import('zod')['z'];
}
