when:
  - event: [push, pull_request, tag, deployment]

steps:
  - name: trivy-scan
    image: woodpeckerci/plugin-trivy
    settings:
      dir: .
      severity: HIGH,CRITICAL
      exit-code: 1
      skip-dirs: vendor,node_modules
    when:
      - event: [push, pull_request]

  - name: build
    image: bun
    commands:
      - bun install --production
      - bun run build
    when:
      - event: [pull_request]

  - name: docker-push
    image: woodpeckerci/plugin-kaniko
    settings:
      registry:
        from_secret: DOCKER_REGISTRY
      repo: minecraft-server-manager
      tags:
        - latest
        - ${CI_COMMIT_TAG:-${CI_COMMIT_SHA}}
      dockerfile: Dockerfile
      context: .
      build-args:
        NODE_ENV: production
      docker-config-json:
        from_secret: docker-config-json
    when:
      - event: push
        branch: main
      - event: tag

  - name: discord-success
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      username: minecraft-server-manager CI
      message: |
        ✅ Build #{{build.number}} succeeded
        > **Repo**: ${CI_REPO}
        > **Branch**: ${CI_COMMIT_BRANCH}
        > **Commit**: ${CI_COMMIT_SHA:0:8} | ${CI_COMMIT_SHA}
        > **Message**: ${CI_COMMIT_MESSAGE}
        > **Author**: ${CI_COMMIT_AUTHOR}
        > **Link**: {{build.link}}
        > **Forge**: ${CI_PIPELINE_FORGE_URL}
    when:
      - event: [push, pull_request, tag]
        status: [success]

  - name: discord-failure
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      username: minecraft-server-manager CI
      message: |
        ❌ Build #{{build.number}} failed
        > **Repo**: ${CI_REPO}
        > **Branch**: ${CI_COMMIT_BRANCH}
        > **Commit**: ${CI_COMMIT_SHA:0:8} | ${CI_COMMIT_SHA}
        > **Message**: ${CI_COMMIT_MESSAGE}
        > **Author**: ${CI_COMMIT_AUTHOR}
        > **Link**: {{build.link}}
        > **Forge**: ${CI_PIPELINE_FORGE_URL}
    when:
      - event: [push, pull_request, tag]
        status: [failure]

  - name: discord-event
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      username: minecraft-server-manager CI
      message: |
        📦 ${CI_PIPELINE_EVENT}: ${CI_COMMIT_REF}
        > **Repo**: ${CI_REPO}
        > **Commit**: ${CI_COMMIT_SHA:0:8} | ${CI_COMMIT_SHA}
        > **Message**: ${CI_COMMIT_MESSAGE}
        > **Author**: ${CI_COMMIT_AUTHOR}
        > **Link**: {{build.link}}
        > **Forge**: ${CI_PIPELINE_FORGE_URL}
    when:
      - event: [deployment]
